DATA = [
    {
        "Name": "Advanced ARC Powercell",
        "Rarity": "Rare",
        "Recycles To": "2x ARC Powercell",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Misc",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Advanced Electrical Components",
        "Rarity": "Rare",
        "Recycles To": "1x Electrical Components 1x Wires",
        "Sell Price": "1,750",
        "Max Stack Size": "5",
        "Category": "Advanced Material",
        "Keep for Quests/Workshop": "5x Workshop 5x Expedition",
    },
    {
        "Name": "Advanced Mechanical Components",
        "Rarity": "Rare",
        "Recycles To": "1x Mechanical Components 1x Wires",
        "Sell Price": "1,750",
        "Max Stack Size": "5",
        "Category": "Advanced Material",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "Agave",
        "Rarity": "Uncommon",
        "Recycles To": "3x Assorted Seeds",
        "Sell Price": "1,000",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Air Freshener",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "5",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Alarm Clock",
        "Rarity": "Rare",
        "Recycles To": "1x Processor 6x Plastic Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Antiseptic",
        "Rarity": "Rare",
        "Recycles To": "10x Chemicals",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "8x Workshop2x Quest",
    },
    {
        "Name": "Apricot",
        "Rarity": "Uncommon",
        "Recycles To": "3x Assorted Seeds",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "15x Scrappy",
    },
    {
        "Name": "ARC Alloy",
        "Rarity": "Uncommon",
        "Recycles To": "2x Metal Parts",
        "Sell Price": "200",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "18x Workshop 80x Expedition",
    },
    {
        "Name": "ARC Circuitry",
        "Rarity": "Rare",
        "Recycles To": "2x ARC Alloy",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "10x Workshop",
    },
    {
        "Name": "ARC Coolant",
        "Rarity": "Rare",
        "Recycles To": "16x Chemicals",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "ARC Flex Rubber",
        "Rarity": "Rare",
        "Recycles To": "16x Rubber Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "ARC Motion Core",
        "Rarity": "Rare",
        "Recycles To": "2x ARC Alloy",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "ARC Performance Steel",
        "Rarity": "Rare",
        "Recycles To": "12x Metal Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "ARC Powercell",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "270",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "ARC Synthetic Resin",
        "Rarity": "Rare",
        "Recycles To": "14x Plastic Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "ARC Thermo Lining",
        "Rarity": "Rare",
        "Recycles To": "16x Fabric",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Assorted Seeds",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "100",
        "Category": "Nature",
        "Keep for Quests/Workshop": "Currency for Celeste",
    },
    {
        "Name": "Bastion Cell",
        "Rarity": "Epic",
        "Recycles To": "2x ARC Motion Core 2x Advanced Mechanical Components",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "6x Workshop",
    },
    {
        "Name": "Battery",
        "Rarity": "Uncommon",
        "Recycles To": "2x Metal Parts",
        "Sell Price": "250",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "30x Expedition",
    },
    {
        "Name": "Bicycle Pump",
        "Rarity": "Rare",
        "Recycles To": "4x Canister 10x Metal Parts",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Bloated Tuna Can",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "15",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Blue Gate Communication Tower Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Blue Gate Confiscation Room Key",
        "Rarity": "Epic",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Blue Gate Cellar Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Blue Gate Village Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Bombardier Cell",
        "Rarity": "Epic",
        "Recycles To": "2x Advanced Mechanical Components 2x ARC Alloy",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "6x Workshop",
    },
    {
        "Name": "Breathtaking Snow Globe",
        "Rarity": "Epic",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "7,000",
        "Max Stack Size": "1",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Broken Flashlight",
        "Rarity": "Rare",
        "Recycles To": "2x Battery 6x Metal Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Broken Guidance System",
        "Rarity": "Rare",
        "Recycles To": "4x Processor",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Broken Handheld Radio",
        "Rarity": "Rare",
        "Recycles To": "3x Sensors 3x Wires",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Broken Taser",
        "Rarity": "Rare",
        "Recycles To": "2x Battery 2x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Buried City Hospital Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Buried City JKV Employee Access Card",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Buried City Residential Mastery Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Buried City Town Hall Key",
        "Rarity": "Epic",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Burned ARC Circuitry",
        "Rarity": "Uncommon",
        "Recycles To": "2x ARC Alloy",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Camera Lens",
        "Rarity": "Uncommon",
        "Recycles To": "8x Plastic Parts",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Candle Holder",
        "Rarity": "Uncommon",
        "Recycles To": "8x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Canister",
        "Rarity": "Uncommon",
        "Recycles To": "3x Plastic Parts",
        "Sell Price": "300",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Cat Bed",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "1x Scrappy",
    },
    {
        "Name": "Chemicals",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "50",
        "Max Stack Size": "50",
        "Category": "Basic Material",
        "Keep for Quests/Workshop": "50x Workshop",
    },
    {
        "Name": "Coffee Pot",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Complex Gun Parts",
        "Rarity": "Epic",
        "Recycles To": "3x Simple Gun Parts",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Coolant",
        "Rarity": "Rare",
        "Recycles To": "5x Chemicals 2x Oil",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Cooling Coil",
        "Rarity": "Rare",
        "Recycles To": "6x Chemicals 2x Steel Spring",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Cooling Fan",
        "Rarity": "Rare",
        "Recycles To": "14x Plastic Parts 4x Battery",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "5x Expedition",
    },
    {
        "Name": "Cracked Bioscanner",
        "Rarity": "Rare",
        "Recycles To": "3x Rubber Parts 5x Battery",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "2x Workshop",
    },
    {
        "Name": "Crude Explosives",
        "Rarity": "Uncommon",
        "Recycles To": "3x Chemicals",
        "Sell Price": "270",
        "Max Stack Size": "10",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "Crumpled Plastic Bottle",
        "Rarity": "Uncommon",
        "Recycles To": "3x Plastic Parts",
        "Sell Price": "270",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dam Control Tower Key",
        "Rarity": "Epic",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dam Staff Room Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dam Surveillance Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dam Testing Annex Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dam Utility Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged ARC Motion Core",
        "Rarity": "Uncommon",
        "Recycles To": "2x ARC Alloy",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged ARC Powercell",
        "Rarity": "Common",
        "Recycles To": "1x ARC Alloy",
        "Sell Price": "293",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged Fireball Burner",
        "Rarity": "Common",
        "Recycles To": "1x ARC Alloy",
        "Sell Price": "270",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged Heat Sink",
        "Rarity": "Rare",
        "Recycles To": "6x Metal Parts 2x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "2x Workshop",
    },
    {
        "Name": "Damaged Hornet Driver",
        "Rarity": "Common",
        "Recycles To": "2x ARC Alloy",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged Rocketeer Driver",
        "Rarity": "Common",
        "Recycles To": "3x ARC Alloy",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged Snitch Scanner",
        "Rarity": "Common",
        "Recycles To": "-",
        "Sell Price": "659",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged Tick Pod",
        "Rarity": "Common",
        "Recycles To": "1x ARC Alloy",
        "Sell Price": "270",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Damaged Wasp Driver",
        "Rarity": "Common",
        "Recycles To": "1x ARC Alloy",
        "Sell Price": "270",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dart Board",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Deflated Football",
        "Rarity": "Uncommon",
        "Recycles To": "15x Rubber Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Degraded ARC Rubber",
        "Rarity": "Uncommon",
        "Recycles To": "11x Rubber Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Diving Goggles",
        "Rarity": "Rare",
        "Recycles To": "12x Rubber Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Dog Collar",
        "Rarity": "Rare",
        "Recycles To": "8x Fabric 1x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "1x Scrappy",
    },
    {
        "Name": "Dried-Out ARC Resin",
        "Rarity": "Uncommon",
        "Recycles To": "9x Plastic Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Duct Tape",
        "Rarity": "Uncommon",
        "Recycles To": "3x Fabric",
        "Sell Price": "300",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Durable Cloth",
        "Rarity": "Uncommon",
        "Recycles To": "6x Fabric",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "5x Workshop 35x Expedition 1x Quest",
    },
    {
        "Name": "Electrical Components",
        "Rarity": "Uncommon",
        "Recycles To": "3x Plastic Parts 3x Rubber Parts",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "10x Workshop 30x Expedition",
    },
    {
        "Name": "Empty Wine Bottle",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Exodus Modules",
        "Rarity": "Epic",
        "Recycles To": "2x Magnet 1x Mechanical Components",
        "Sell Price": "2,750",
        "Max Stack Size": "3",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "1x Expedition",
    },
    {
        "Name": "Expired Pasta",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "15",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Expired Respirator",
        "Rarity": "Rare",
        "Recycles To": "8x Rubber Parts 4x Fabric",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Explosive Compound",
        "Rarity": "Rare",
        "Recycles To": "2x Crude Explosives",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "Fabric",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "50",
        "Max Stack Size": "50",
        "Category": "Basic Material",
        "Keep for Quests/Workshop": "80x Workshop",
    },
    {
        "Name": "Faded Photograph",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "640",
        "Max Stack Size": "15",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "2x Quest",
    },
    {
        "Name": "Fertilizer",
        "Rarity": "Uncommon",
        "Recycles To": "2x Assorted Seeds",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Nature",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Film Reel",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Fine Wristwatch",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Fireball Burner",
        "Rarity": "Uncommon",
        "Recycles To": "1x ARC Alloy 1x Chemicals",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "8x Workshop",
    },
    {
        "Name": "Frequency Modulation Box",
        "Rarity": "Rare",
        "Recycles To": "1x Advanced Electrical Components1x Speaker Component",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Fried Motherboard",
        "Rarity": "Rare",
        "Recycles To": "5x Plastic Parts 1x Electrical Components",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Frying Pan",
        "Rarity": "Rare",
        "Recycles To": "8x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Garlic Press",
        "Rarity": "Uncommon",
        "Recycles To": "12x Metal Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Geiger Counter",
        "Rarity": "Epic",
        "Recycles To": "3x Battery 1x Exodus Modules",
        "Sell Price": "3,500",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Great Mullein",
        "Rarity": "Uncommon",
        "Recycles To": "4x Assorted Seeds",
        "Sell Price": "300",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Headphones",
        "Rarity": "Rare",
        "Recycles To": "6x Rubber Parts 2x Speaker Component",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Heavy Gun Parts",
        "Rarity": "Rare",
        "Recycles To": "2x Simple Gun Parts",
        "Sell Price": "700",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Hornet Driver",
        "Rarity": "Rare",
        "Recycles To": "2x ARC Alloy 2x Electrical Components",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "5x Workshop2x Quest",
    },
    {
        "Name": "Household Cleaner",
        "Rarity": "Uncommon",
        "Recycles To": "13x Chemicals",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Humidifier",
        "Rarity": "Rare",
        "Recycles To": "2x Canister 2x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "5x Expedition",
    },
    {
        "Name": "Ice Cream Scooper",
        "Rarity": "Uncommon",
        "Recycles To": "7x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Impure ARC Coolant",
        "Rarity": "Uncommon",
        "Recycles To": "13x Chemicals",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Industrial Battery",
        "Rarity": "Rare",
        "Recycles To": "7x Chemicals 2x Battery",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Industrial Charger",
        "Rarity": "Rare",
        "Recycles To": "5x Metal Parts 1x Voltage Converter",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Industrial Magnet",
        "Rarity": "Rare",
        "Recycles To": "2x Magnet 4x Metal Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ion Sputter",
        "Rarity": "Epic",
        "Recycles To": "4x Voltage Converter 1x Exodus Modules",
        "Sell Price": "6,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Laboratory Reagents",
        "Rarity": "Rare",
        "Recycles To": "2x Chemicals 2x Crude Explosives",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Lance's Mixtape (5th Edition)",
        "Rarity": "Epic",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "10,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Lemon",
        "Rarity": "Common",
        "Recycles To": "3x Assorted Seeds",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "3x Scrappy",
    },
    {
        "Name": "Leaper Pulse Unit",
        "Rarity": "Epic",
        "Recycles To": "2x Advanced Mechanical Components 3x ARC Alloy",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Expedition 4x Workshop",
    },
    {
        "Name": "Light Bulb",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "5x Expedition",
    },
    {
        "Name": "Light Gun Parts",
        "Rarity": "Rare",
        "Recycles To": "2x Simple Gun Parts",
        "Sell Price": "700",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Magnet",
        "Rarity": "Uncommon",
        "Recycles To": "3x Metal Parts",
        "Sell Price": "300",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Magnetic Accelerator",
        "Rarity": "Epic",
        "Recycles To": "1x Advanced Mechanical Components 1x ARC Motion Core",
        "Sell Price": "5,500",
        "Max Stack Size": "3",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "3x Expedition",
    },
    {
        "Name": "Magnetron",
        "Rarity": "Epic",
        "Recycles To": "1x Magnetic Accelerator1x Steel Spring",
        "Sell Price": "6,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Matriarch Reactor",
        "Rarity": "Legendary",
        "Recycles To": "1x Power Rod 1x Magnetic Accelerator",
        "Sell Price": "13,000",
        "Max Stack Size": "1",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Mechanical Components",
        "Rarity": "Uncommon",
        "Recycles To": "3x Metal Parts 2x Rubber Parts",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Refined Material",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "Medium Gun Parts",
        "Rarity": "Rare",
        "Recycles To": "2x Simple Gun Parts",
        "Sell Price": "700",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Metal Brackets",
        "Rarity": "Uncommon",
        "Recycles To": "8x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Metal Parts",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "75",
        "Max Stack Size": "50",
        "Category": "Basic Material",
        "Keep for Quests/Workshop": "80x Workshop 150x Expedition",
    },
    {
        "Name": "Microscope",
        "Rarity": "Rare",
        "Recycles To": "1x Advanced Mechanical Components 3x Magnet",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Mini Centrifuge",
        "Rarity": "Rare",
        "Recycles To": "1x Advanced Mechanical Components 2x Canister",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Mod Components",
        "Rarity": "Epic",
        "Recycles To": "1x Mechanical Components 1x Steel Spring",
        "Sell Price": "1,750",
        "Max Stack Size": "3",
        "Category": "Advanced Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Moss",
        "Rarity": "Rare",
        "Recycles To": "3x Assorted Seeds",
        "Sell Price": "500",
        "Max Stack Size": "10",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Motor",
        "Rarity": "Rare",
        "Recycles To": "2x Oil 2x Mechanical Components",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Mushroom",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "12x Scrappy",
    },
    {
        "Name": "Music Album",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Music Box",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Number Plate",
        "Rarity": "Uncommon",
        "Recycles To": "3x Metal Parts",
        "Sell Price": "270",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Oil",
        "Rarity": "Uncommon",
        "Recycles To": "3x Chemicals",
        "Sell Price": "300",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Olives",
        "Rarity": "Common",
        "Recycles To": "2x Assorted Seeds",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "6x Scrappy",
    },
    {
        "Name": "Painted Box",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Patrol Car Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Plastic Parts",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "60",
        "Max Stack Size": "50",
        "Category": "Basic Material",
        "Keep for Quests/Workshop": "75x Workshop",
    },
    {
        "Name": "Playing Cards",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Polluted Air Filter",
        "Rarity": "Rare",
        "Recycles To": "6x Fabric 2x Oil",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Pop Trigger",
        "Rarity": "Common",
        "Recycles To": "1x Crude Explosives 1x ARC Alloy",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "5x Workshop",
    },
    {
        "Name": "Portable TV",
        "Rarity": "Rare",
        "Recycles To": "2x Battery6x Wires",
        "Sell Price": "2,000",
        "Max Stack Size": "1",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Poster of Natural Wonders",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Pottery",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Power Bank",
        "Rarity": "Rare",
        "Recycles To": "2x Battery 2x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Power Cable",
        "Rarity": "Rare",
        "Recycles To": "4x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Power Rod",
        "Rarity": "Epic",
        "Recycles To": "1x Advanced Electrical Components 1x ARC Circuitry",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Advanced Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Prickly Pear",
        "Rarity": "Common",
        "Recycles To": "3x Assorted Seeds",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "6x Scrappy",
    },
    {
        "Name": "Processor",
        "Rarity": "Rare",
        "Recycles To": "1x Wires1x Plastic Parts",
        "Sell Price": "500",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Projector",
        "Rarity": "Rare",
        "Recycles To": "1x Processor2x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Queen Reactor",
        "Rarity": "Legendary",
        "Recycles To": "1x Power Rod 1x Magnetic Accelerator",
        "Sell Price": "13,000",
        "Max Stack Size": "1",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Radio",
        "Rarity": "Rare",
        "Recycles To": "1x Speaker Component 1x Sensors",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Radio Relay",
        "Rarity": "Rare",
        "Recycles To": "2x Speaker Component2x Sensors",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Raider Hatch Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Red Coral Jewelry",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Remote Control",
        "Rarity": "Uncommon",
        "Recycles To": "2x Plastic Parts 1x Sensors",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Resin",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ripped Safety Vest",
        "Rarity": "Uncommon",
        "Recycles To": "1x Magnet 1x Durable Cloth",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rocket Thruster",
        "Rarity": "Rare",
        "Recycles To": "2x Synthesized Fuel 6x Metal Parts",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rocketeer Driver",
        "Rarity": "Epic",
        "Recycles To": "2x Advanced Electrical Components 3x ARC Alloy",
        "Sell Price": "5,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Roots",
        "Rarity": "Uncommon",
        "Recycles To": "1x Assorted Seeds",
        "Sell Price": "640",
        "Max Stack Size": "10",
        "Category": "Nature",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rope",
        "Rarity": "Rare",
        "Recycles To": "5x Fabric",
        "Sell Price": "500",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rosary",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rotary Encoder",
        "Rarity": "Rare",
        "Recycles To": "2x Electrical Components 2x Processor",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rubber Duck",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "15",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rubber Pad",
        "Rarity": "Rare",
        "Recycles To": "18x Rubber Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rubber Parts",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "50",
        "Max Stack Size": "50",
        "Category": "Basic Material",
        "Keep for Quests/Workshop": "30x Workshop 200x Expedition",
    },
    {
        "Name": "Ruined Accordion",
        "Rarity": "Rare",
        "Recycles To": "18x Rubber Parts 3x Steel Spring",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ruined Augment",
        "Rarity": "Common",
        "Recycles To": "2x Plastic Parts 2x Rubber Parts",
        "Sell Price": "270",
        "Max Stack Size": "1",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ruined Baton",
        "Rarity": "Uncommon",
        "Recycles To": "6x Metal Parts 3x Rubber Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ruined Handcuffs",
        "Rarity": "Uncommon",
        "Recycles To": "8x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ruined Parachute",
        "Rarity": "Uncommon",
        "Recycles To": "10x Fabric",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ruined Tactical Vest",
        "Rarity": "Uncommon",
        "Recycles To": "5x Fabric 1x Magnet",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Ruined Riot Shield",
        "Rarity": "Rare",
        "Recycles To": "10x Plastic Parts 6x Rubber Parts",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rusted Bolts",
        "Rarity": "Uncommon",
        "Recycles To": "8x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Rusted Gear",
        "Rarity": "Rare",
        "Recycles To": "4x Metal Parts 2x Mechanical Components",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Rusted Shut Medical Kit",
        "Rarity": "Rare",
        "Recycles To": "2x Syringe 1x Antiseptic",
        "Sell Price": "2,000",
        "Max Stack Size": "1",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Rusted Tools",
        "Rarity": "Rare",
        "Recycles To": "8x Metal Parts 1x Steel Spring",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Rusty ARC Steel",
        "Rarity": "Uncommon",
        "Recycles To": "8x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Sample Cleaner",
        "Rarity": "Rare",
        "Recycles To": "2x Electrical Components14x Assorted Seeds",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Sensors",
        "Rarity": "Rare",
        "Recycles To": "2x Wires 2x Metal Parts",
        "Sell Price": "500",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "20x Expedition",
    },
    {
        "Name": "Sentinel Firing Core",
        "Rarity": "Rare",
        "Recycles To": "2x ARC Alloy 3x Mechanical Components",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "4x Workshop",
    },
    {
        "Name": "Shredder Gyro",
        "Rarity": "Uncommon",
        "Recycles To": "3x Mechanical Components 3x ARC Alloy",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Signal Amplifier",
        "Rarity": "Rare",
        "Recycles To": "2x Electrical Components 2x Voltage Converter",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Silver Teaspoon Set",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Simple Gun Parts",
        "Rarity": "Uncommon",
        "Recycles To": "2x Metal Parts",
        "Sell Price": "330",
        "Max Stack Size": "10",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Snitch Scanner",
        "Rarity": "Uncommon",
        "Recycles To": "4x ARC Alloy 2x Electrical Components",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "6x Workshop",
    },
    {
        "Name": "Spaceport Container Storage Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Spaceport Control Tower Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Spaceport Trench Tower Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Spaceport Warehouse Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Speaker Component",
        "Rarity": "Rare",
        "Recycles To": "2x Plastic Parts 2x Rubber Parts",
        "Sell Price": "500",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Spectrometer",
        "Rarity": "Rare",
        "Recycles To": "1x Advanced Electrical Components1x Sensors",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Spectrum Analyzer",
        "Rarity": "Epic",
        "Recycles To": "1x Sensors 1x Exodus Modules",
        "Sell Price": "3,500",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Spring Cushion",
        "Rarity": "Rare",
        "Recycles To": "2x Durable Cloth 2x Steel Spring",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Spotter Relay",
        "Rarity": "Uncommon",
        "Recycles To": "2x Electrical Components 1x ARC Alloy",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Statuette",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Steel Spring",
        "Rarity": "Uncommon",
        "Recycles To": "3x Metal Parts",
        "Sell Price": "300",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "15x Expedition",
    },
    {
        "Name": "Stella Montis Archives Key",
        "Rarity": "Epic",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Stella Montis Assembly Admin Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Stella Montis Medical Storage Key",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Stella Montis Security Checkpoint Key",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "100",
        "Max Stack Size": "1",
        "Category": "Key",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Surveyor Vault",
        "Rarity": "Rare",
        "Recycles To": "2x Mechanical Components 2x ARC Alloy",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "5x Workshop 1x Quest",
    },
    {
        "Name": "Synthesized Fuel",
        "Rarity": "Rare",
        "Recycles To": "1x Oil 1x Plastic Parts",
        "Sell Price": "700",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Syringe",
        "Rarity": "Rare",
        "Recycles To": "3x Plastic Parts 2x Chemicals",
        "Sell Price": "500",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Tattered ARC Lining",
        "Rarity": "Uncommon",
        "Recycles To": "12x Fabric",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Tattered Clothes",
        "Rarity": "Uncommon",
        "Recycles To": "11x Fabric",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Telemetry Transceiver",
        "Rarity": "Rare",
        "Recycles To": "1x Advanced Electrical Components1x Processor",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Thermostat",
        "Rarity": "Rare",
        "Recycles To": "6x Rubber Parts 2x Sensors",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Tick Pod",
        "Rarity": "Uncommon",
        "Recycles To": "1x Chemicals 1x Metal Parts",
        "Sell Price": "640",
        "Max Stack Size": "5",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "8x Workshop",
    },
    {
        "Name": "Toaster",
        "Rarity": "Rare",
        "Recycles To": "5x Plastic Parts 3x Wires",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "3x Workshop",
    },
    {
        "Name": "Torn Book",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "1,000",
        "Max Stack Size": "5",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Torn Blanket",
        "Rarity": "Rare",
        "Recycles To": "12x Fabric",
        "Sell Price": "640",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Turbo Pump",
        "Rarity": "Rare",
        "Recycles To": "1x Mechanical Components 3x Oil",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Unusable Weapon",
        "Rarity": "Rare",
        "Recycles To": "4x Metal Parts 5x Simple Gun Parts",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Vase",
        "Rarity": "Rare",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "3,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Very Comfortable Pillow",
        "Rarity": "Uncommon",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "2,000",
        "Max Stack Size": "3",
        "Category": "Trinket",
        "Keep for Quests/Workshop": "3x Scrappy",
    },
    {
        "Name": "Volcanic Rock",
        "Rarity": "Common",
        "Recycles To": "Cannot be recycled",
        "Sell Price": "270",
        "Max Stack Size": "5",
        "Category": "Misc",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Voltage Converter",
        "Rarity": "Rare",
        "Recycles To": "1x Wires 1x Rubber Parts",
        "Sell Price": "500",
        "Max Stack Size": "5",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Wasp Driver",
        "Rarity": "Rare",
        "Recycles To": "1x ARC Alloy 1x Electrical Components", 
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "8x Workshop",
    },
    {
        "Name": "Water Filter",
        "Rarity": "Rare",
        "Recycles To": "2x Rubber Parts 3x Canister",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "",
    },
    {
        "Name": "Water Pump",
        "Rarity": "Rare",
        "Recycles To": "4x Metal Parts 2x Oil",
        "Sell Price": "1,000",
        "Max Stack Size": "3",
        "Category": "Recyclable",
        "Keep for Quests/Workshop": "1x Quest",
    },
    {
        "Name": "Wires",
        "Rarity": "Uncommon",
        "Recycles To": "2x Rubber Parts",
        "Sell Price": "200",
        "Max Stack Size": "15",
        "Category": "Topside Material",
        "Keep for Quests/Workshop": "30x Expedition 3x Quest",
    },
]
